name: Build & Test

on:
  pull_request:
    branches: [ dev-master ]

env:
  ASOFT_MAVEN_PGP_PRIVATE_KEY: ${{ secrets.ASOFT_MAVEN_PGP_PRIVATE_KEY }}
  ASOFT_MAVEN_PGP_PASSWORD: ${{ secrets.ASOFT_MAVEN_PGP_PASSWORD }}

jobs:
  checking-library-samples-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Building samples/library-samples/android-library
        run: |
          chmod +x ./gradlew
          ./gradlew publishToMavenLocal
        working-directory: ./samples/library-samples/android-library

  checking-library-samples-browser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Building samples/js-library
        run: |
          chmod +x ./gradlew
          ./gradlew publishToMavenLocal
        working-directory: ./samples/library-samples/js-library

  checking-library-samples-jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Building samples/library-samples/jvm-library
        run: |
          chmod +x ./gradlew
          ./gradlew publishToMavenLocal
        working-directory: ./samples/library-samples/jvm-library

  checking-library-samples-multiplatform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Building samples/library-samples/multiplatform-library
        run: |
          chmod +x ./gradlew
          ./gradlew publishToMavenLocal
        working-directory: ./samples/library-samples/multiplatform-library

  checking-applikation-samples-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Building samples/applikation-samples/android-applikation
        run: |
          chmod +x ./gradlew
          ./gradlew :assembleDebug
        working-directory: ./samples/applikation-samples/android-applikation

  checking-applikation-samples-browser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Building samples/applikation-samples/browser-applikation
        run: |
          chmod +x ./gradlew
          ./gradlew :webpackRelease
        working-directory: ./samples/applikation-samples/browser-applikation

  checking-applikation-samples-desktop-applikation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Building samples/applikation-samples/desktop-applikation
        run: |
          chmod +x ./gradlew
          ./gradlew :installDistRelease
        working-directory: ./samples/applikation-samples/desktop-applikation

  checking-applikation-samples-multiplatform-applikation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Making gradlew executable
        run: chmod +x ./gradlew
        working-directory: ./samples/applikation-samples/multiplatform-applikation
      - name: Building android applikation
        run: ./gradlew :assembleDebug
        working-directory: ./samples/applikation-samples/multiplatform-applikation
      - name: Building desktop applikation
        run: ./gradlew :fatJarJvmRelease
        working-directory: ./samples/applikation-samples/multiplatform-applikation
      - name: Building browser applikation
        run: ./gradlew :webpackJsRelease
        working-directory: ./samples/applikation-samples/multiplatform-applikation

  checking-applikation-samples-multimodule-applikation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Building samples/applikation-samples/desktop-applikation
        run: |
          chmod +x ./gradlew
          ./gradlew :todo-browser:webpackRelease
        working-directory: ./samples/applikation-samples/multimodule-applikation

  building-applikation-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Building applikation-runtime
        run: |
          chmod +x ./gradlew
          ./gradlew :build
        working-directory: ./applikation-runtime
